export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY';
export const DOCUMENT_REPOSITORY = 'DOCUMENT_REPOSITORY';
export const FOLDER_REPOSITORY = 'FOLDER_REPOSITORY';
export const COMPANY_MEMBER_REPOSITORY = 'COMPANY_MEMBER_REPOSITORY';
export const CONVERSATION_REPOSITORY = 'CONVERSATION_REPOSITORY';
export const CONVERSATION_MESSAGES_REPOSITORY =
  'CONVERSATION_MESSAGES_REPOSITORY';
export const ADMIN_REPOSITORY = 'ADMIN_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const ADMIN_ROLE_REPOSITORY = 'ADMIN_ROLE_REPOSITORY';
export const CHECKLIST_REPOSITORY = 'COMPANY_CHECKLIST_REPOSITORY';
export const VAULT_REPOSITORY = 'VAULT_REPOSITORY';
export const COMPLIANCE_REPOSITORY = 'COMPLIANCE_REPOSITORY';
export const TASK_REPOSITORY = 'COMPLIANCE_TASK_REPOSITORY';
export const COMPANY_TASK_REPOSITORY = 'COMPANY_TASK_REPOSITORY';
export const COMPLIANCE_DOCUMENT_REPOSITORY = 'COMPLIANCE_DOCUMENT_REPOSITORY';
export const COMPANY_TASK_DOCUMENT_REPOSITORY =
  'COMPANY_TASK_DOCUMENT_REPOSITORY';
export const NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY';
export const NOTIFICATION_OBJECT_REPOSITORY = 'NOTIFICATION_OBJECT_REPOSITORY';
export const NOTIFICATION_CHANGE_REPOSITORY = 'NOTIFICATION_CHANGE_REPOSITORY';
export const CORRECT_COLLECTION = 'correct';
export const AGENT_ID = 'orchestratorAgent';

export const jwtConstants = {
  secret: '892ba2f483254717847b31e7934574b778b8267b4db5616f918ee273ac585464',
  expiresIn: '7d',
};

export const bcryptConstants = {
  saltOrRounds: 10,
};

export const OTP_EXPIRATION_TIME = 5;
export const OTP_LENGTH = 6;
export const CACHE_TTL = 1 * 60 * 1000;
export const CACHE_MAX_ITEMS = 1000;
